theme: jekyll-theme-slate
site_favicon: favicon.ico
title: NPUHeart 项目
description: IB method for cardiac simulation

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: "NPUHeart 项目"

url: https://npuheart.github.io
